# ######################################################
## General
CONFIG_ZMK_KEYBOARD_NAME="Corne"

### Power
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=120000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Make Bluetooth stronger
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_0=y

# Decrease profiles to 2 (+1 for split)
# CONFIG_BT_MAX_CONN=3
# CONFIG_BT_MAX_PAIRED=3

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=12

# Better key tracking for fast typing with home-row mods
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Less frequent battery reports save BLE bandwidth & a bit of power
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=300

# Windows battery reporting fix
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Disable external power when not connected to USB
# CONFIG_ZMK_EXT_POWER_USB_ONLY=y

# Custom nice!view board
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_GEM_ANIMATION=n
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=8000
# CONFIG_NICE_VIEW_GEM_ANIMATION_FRAME=8
